### ISSUE TITLE
No python 3.11 distribution in PyPI

### ISSUE THREAD

**Issue by CaseyTa** [Knowledge-Graph-Hub/rustsim#31]
There doesn't seem to be any distributions for any version of rustsim for Python 3.11 on PyPI. Looks like it's expected to be supported for Python >= 3.7. PyPI shows built distributions for 3.7-3.10: https://pypi.org/project/rustsim/#files. 

Here's the message I see when I manually try to install rustsim in a Python 3.11 environment: 
```
pip install rustsim
ERROR: Could not find a version that satisfies the requirement rustsim (from versions: 0.1.9)
ERROR: No matching distribution found for rustsim
```

For background: For NCATS Biomedical Data Translator, we're using the biolink modeling toolkit, which depends on oaklib, which depends on rustsim. Please let me know if any other info may be needed.

**Comment by caufieldjh** [comment]
Thanks @CaseyTa - we'll add a Python 3.11 build.

**Comment by caufieldjh** [comment]
OK, rustsim wheel for 3.11 is now on Pypi.

**Comment by CaseyTa** [comment]
Thank you, @caufieldjh! Confirmed that my pipelines are working as expected now. Very much appreciate the quick resolution! Also, excellent presentation today :)

**Comment by caufieldjh** [comment]
Thanks!
