### ISSUE TITLE
Feature request: providing a linux-arm64 build

### ISSUE THREAD

**Issue by gouttegd** [Knowledge-Graph-Hub/rustsim#38]
Hi,

Could it be possible to provide wheels for GNU/Linux on arm64 architecture?

Not familiar with Rust’s build system, but my understanding is that adding [aarch64-unknown-linux-gnu](https://doc.rust-lang.org/nightly/rustc/platform-support.html) (for GNU glibc) and `aarch64-unknown-linux-musl` (for MUSL libc) to the [target matrix](https://github.com/Knowledge-Graph-Hub/rustsim/blob/c30e62c4c68ccc07148964f3477e72445fb51ca3/.github/workflows/qc.yml#L52) should be enough?

**Comment by caufieldjh** [comment]
Sure - done! Should be on Pypi shortly.

**Comment by gouttegd** [comment]
Thanks!
